// <auto-generated />
using System;
using Fakebook.Profile.DataAccess.EntityModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fakebook.Profile.DataAccess.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    partial class ProfileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Fakebook.Profile.DataAccess.EntityModel.EntityFollow", b =>
                {
                    b.Property<string>("FollowerEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FolloweeEmail")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FollowerEmail", "FolloweeEmail")
                        .HasName("Pk_FollowEntity");

                    b.HasIndex("FolloweeEmail");

                    b.ToTable("Follow", "Fakebook");
                });

            modelBuilder.Entity("Fakebook.Profile.DataAccess.EntityModel.EntityProfile", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("Profile", "Fakebook");
                });

            modelBuilder.Entity("Fakebook.Profile.DataAccess.EntityModel.EntityFollow", b =>
                {
                    b.HasOne("Fakebook.Profile.DataAccess.EntityModel.EntityProfile", "Followee")
                        .WithMany("Followers")
                        .HasForeignKey("FolloweeEmail")
                        .HasConstraintName("Fk_Follow_Followee")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fakebook.Profile.DataAccess.EntityModel.EntityProfile", "Follower")
                        .WithMany("Followees")
                        .HasForeignKey("FollowerEmail")
                        .HasConstraintName("Fk_Follow_Follower")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Followee");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("Fakebook.Profile.DataAccess.EntityModel.EntityProfile", b =>
                {
                    b.Navigation("Followees");

                    b.Navigation("Followers");
                });
#pragma warning restore 612, 618
        }
    }
}
