---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakebook-profile-api
  labels:
    app: fakebook-profile
    role: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakebook-profile
      role: api
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fakebook-profile
        role: api
    spec:
      containers:
      - name: api
        image: fakebookprofile:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__Default
          value: 'Host=fakebook-profile-db;Database=postgres;Username=postgres;Password=Pass@word'
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakebook-profile-db
  labels:
    app: fakebook-profile
    role: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakebook-profile
      role: db
  template:
    metadata:
      labels:
        app: fakebook-profile
        role: db
    spec:
      containers:
      - name: db
        image: fakebookprofile-db:latest
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-volume
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: fakebook-profile
