---
apiVersion: v1
kind: Service
metadata:
  name: fakebook-profile-api
  labels:
    app: fakebook-profile
    role: api
spec:
  ports:
  - port: 80
  selector:
    app: fakebook-profile
    role: api
---
apiVersion: v1
kind: Service
metadata:
  name: fakebook-profile-db
  labels:
    app: fakebook-profile
    role: db
spec:
  ports:
  - port: 5432
  selector:
    app: fakebook-profile
    role: db
